### ISSUE TITLE
业务数据集上测试效果很差，请问是否在训练的时候需要加上SFT loss

### ISSUE THREAD

**Issue by rookiebird** [wutaiqiang/LLM_KD_AKL#1]
你好，看了你在知乎上的文章过来了，没有太多的蒸馏经验，还是想请教下：

1. 我在自己的业务数据集上使用了本文的方法， 但是没有加上SFT loss， 但是纯distill loss 已经降到 0.1 以下，但是评测的时候效果非常差，感觉似乎没有学到东西。
2. 后续加上SFT loss 后， 发现 distill loss 很快下降，但是 SFT loss 下降得没有 纯 SFT 的方式快，最后的测评效果也没有特别好，想问下 这种结果是不是说 ，蒸馏部分的损失 影响了本身SFT loss 的下降？

**Comment by rookiebird** [comment]
还有一个地方是，我因为资源的限制，student 并不是全量的，而是通过lora 的方式学习的，可能这个也是一个蒸馏效果不好的原因

**Comment by wutaiqiang** [comment]
你好, 很高兴与你讨论. 蒸馏相比于直接 sft 以外, 除了 label 的知识(one-hot)以外,还提供了一定的其他信息(soft label, dark knowledge )等, 也有论文将 KD 的作用定义为 标签平滑 + 类别分类+ 正确 label 三块的知识, 可以参考(https://zhuanlan.zhihu.com/p/607705285). 所以, 按照我的理解, kd 的核心,也就是来自 teacher 的知识, 其实应该是 label 信息的一个补充,但这个补充并不需要过于主导. 基于这个思路,那么你的业务数据集的效果可以这么来看:

1) 只做 sft 的时候是否有效果? 如果纯 sft 就不行,那么sft+kd 大概率也不行,只用 kd 更不行.
2) 在 sft 的基础上, 那么kd loss 这一项不需要过大的比例, 比如 sft loss+0.1 kd loss 就好了.


此外, 针对
```
续加上SFT loss 后， 发现 distill loss 很快下降，但是 SFT loss 下降得没有 纯 SFT 的方式快，最后的测评效果也没有特别好，想问下 这种结果是不是说 ，蒸馏部分的损失 影响了本身SFT loss 的下降？
```

某种意义上来说, sft 的目标和 kd 的目标是很类似的. KD 的作用定义为 标签平滑 + 类别分类+ 正确 label . sft 对应着正确 label 这个能力, 因此 sft loss 的下降也会带来 kd loss 的下降,这是大概率会发生的事情.

**Comment by wutaiqiang** [comment]
> 还有一个地方是，我因为资源的限制，student 并不是全量的，而是通过lora 的方式学习的，可能这个也是一个蒸馏效果不好的原因

使用 lora 做 kd确实会受限, 这点可以参考最近的论文: 

标题: LLM-Neo: Parameter Efficient Knowledge Distillation for Large Language Models
代码: https://arxiv.org/pdf/2411.06839v1
解读: https://zhuanlan.zhihu.com/p/8642629256

一些结论是:

1) 一般来说, rank 越大,承接的效果越好 (微调任务里,rank 不需要太大,但是这里是预训练的知识,因此 rank 需要相对大才有效),上面的实验中, rank=128 效果最优

2) 学习率不宜太大, 2e-4 是一个不错的位置

2) 对于比较大的 rank 值,需要一个相对来说比较小的学习率

**Comment by rookiebird** [comment]
非常感谢作者在百忙之中抽空回复，我补充下后面我实验的结果：
加上SFT loss 之后，效果马上正常了，我实验了三个数据，两个数据集上能够超越原来纯 SFT 的效果。 但是我这里还有个疑惑就是感觉  ”distill loss 的大小似乎不太能表达 学生模型是否很好的拟合教师模型的分布“， 因为在我只用distill loss 的时候， loss 已经非常小了（这里尝试过， fkl, rkl, akl）， 但是最后发现模型的SFT loss 还是很高 (训练的时候只用 distill loss 做反向传播，但是也会打印出 SFT loss 的值作为观察)

再次感谢作者，贴出来的参考内容会好好学习阅读的

**Comment by wutaiqiang** [comment]
这个确实，其实loss和acc也没那么对应。

Loss收敛就行，下游指标还得测着看，根据loss推测下游指标也不靠谱。

你用lora做kd的话，可以参考上面的llm neo 论文
